#!/usr/bin/env python3

import asyncio
from typing import List
async_generator = __import__('0-async_generator').async_generator
"""
This module provides an asynchronous comprehension function
that collects random numbers generated by an async generator.
"""

async def async_comprehension() -> List[float]:
    """
    Asynchronously collects 10 random floating-point numbers
    generated by the async_generator and returns them as a list.
    
    Returns:
        A list of 10 random float numbers collected from async_generator.
    """
    return [number async for number in async_generator()]
